# Generated by Django 2.1.7 on 2019-03-01 07:34

from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('weight', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=100)),
                ('weight', models.IntegerField(blank=True, default=0)),
                ('website', models.URLField()),
                ('twitter', models.CharField(max_length=50)),
                ('full_address', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('location', location_field.models.spatial.LocationField(default='POINT(0.0 0.0)', srid=4326)),
                ('categories', models.ManyToManyField(to='companies.Category')),
                ('cities', models.ManyToManyField(to='geography.City')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='stages',
            field=models.ManyToManyField(to='companies.Stage'),
        ),
    ]
