# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 23:04
from __future__ import unicode_literals

from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20150122_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='location',
            field=location_field.models.spatial.LocationField(default='POINT(0.0 0.0)', srid=4326),
        ),
    ]
