# Generated by Django 2.1.7 on 2019-03-01 07:34

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.spatial


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=255)),
                ('comments', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('distance', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('ecosystem_is_active', models.BooleanField(default=False)),
                ('location', location_field.models.spatial.LocationField(default='POINT(0.0 0.0)', srid=4326)),
                ('hashtags', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('weight', models.IntegerField()),
                ('region', models.CharField(choices=[('NA', 'North America'), ('SA', 'South America'), ('EU', 'Europe'), ('ME', 'Middle East'), ('AS', 'Asia'), ('AU', 'Oceania'), ('AF', 'Africa')], default='NA', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geography.Country'),
        ),
        migrations.AddField(
            model_name='attribution',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='geography.City'),
        ),
    ]
