# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0007_city_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='location',
            field=location_field.models.spatial.LocationField(default='POINT(0.0 0.0)', srid=4326),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('NA', 'North America'), ('SA', 'South America'), ('EU', 'Europe'), ('ME', 'Middle East'), ('AS', 'Asia'), ('AU', 'Oceania'), ('AF', 'Africa')], default='NA', max_length=2),
        ),
    ]
