# Generated by Django 2.1.7 on 2019-03-01 07:34

import apps.tech_events.validators
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.spatial


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, unique=True, validators=[apps.tech_events.validators.validate_meetup_url_exists])),
                ('name', models.CharField(max_length=100)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Meetup Groups',
            },
        ),
        migrations.CreateModel(
            name='ParseError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('error_message', models.TextField()),
                ('payload', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Firehose Parse Errors',
            },
        ),
        migrations.CreateModel(
            name='TechEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('begin_time', models.DateTimeField(verbose_name='begin time')),
                ('source', models.CharField(choices=[('MU', 'Meetup.com'), ('EB', 'EventBrite'), ('IC', '.ics calendar'), ('CU', 'Custom one-off event')], default='CU', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('location', location_field.models.spatial.LocationField(default='POINT (0.0 0.0)', srid=4326)),
                ('meetup_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tech_events.MeetupGroup')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
