# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('tech_events', '0004_auto_20150106_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techevent',
            name='begin_time',
            field=models.DateTimeField(verbose_name='begin time'),
        ),
        migrations.AlterField(
            model_name='techevent',
            name='location',
            field=location_field.models.spatial.LocationField(default='POINT (0.0 0.0)', srid=4326),
        ),
        migrations.AlterField(
            model_name='techevent',
            name='source',
            field=models.CharField(choices=[('MU', 'Meetup.com'), ('EB', 'EventBrite'), ('IC', '.ics calendar'), ('CU', 'Custom one-off event')], default='CU', max_length=2),
        ),
    ]
